// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto

#include <google/protobuf/port_def.inc>
#include <limits>
#include <string>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/message.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>

#include <google/protobuf/port_undef.inc>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_2eproto {
    static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_2eproto;
namespace rpc {
class RpcRequest;
struct RpcRequestDefaultTypeInternal;
extern RpcRequestDefaultTypeInternal _RpcRequest_default_instance_;
class RpcResponse;
struct RpcResponseDefaultTypeInternal;
extern RpcResponseDefaultTypeInternal _RpcResponse_default_instance_;
}  // namespace rpc
PROTOBUF_NAMESPACE_OPEN
template <>
::rpc::RpcRequest *Arena::CreateMaybeMessage<::rpc::RpcRequest>(Arena *);
template <>
::rpc::RpcResponse *Arena::CreateMaybeMessage<::rpc::RpcResponse>(Arena *);
PROTOBUF_NAMESPACE_CLOSE
namespace rpc {

// ===================================================================

class RpcRequest final
    : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rpc.RpcRequest) */ {
public:
    inline RpcRequest() : RpcRequest(nullptr) {}
    ~RpcRequest() override;
    explicit PROTOBUF_CONSTEXPR RpcRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    RpcRequest(const RpcRequest &from);
    RpcRequest(RpcRequest &&from) noexcept : RpcRequest() { *this = ::std::move(from); }

    inline RpcRequest &operator=(const RpcRequest &from) {
        CopyFrom(from);
        return *this;
    }
    inline RpcRequest &operator=(RpcRequest &&from) noexcept {
        if (this == &from) return *this;
        if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
            && GetOwningArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        ) {
            InternalSwap(&from);
        } else {
            CopyFrom(from);
        }
        return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor() { return GetDescriptor(); }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor() {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection() {
        return default_instance().GetMetadata().reflection;
    }
    static const RpcRequest &default_instance() { return *internal_default_instance(); }
    static inline const RpcRequest *internal_default_instance() {
        return reinterpret_cast<const RpcRequest *>(&_RpcRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    friend void swap(RpcRequest &a, RpcRequest &b) { a.Swap(&b); }
    inline void Swap(RpcRequest *other) {
        if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetOwningArena() != nullptr && GetOwningArena() == other->GetOwningArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetOwningArena() == other->GetOwningArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        } else {
            ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(RpcRequest *other) {
        if (other == this) return;
        GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    RpcRequest *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final {
        return CreateMaybeMessage<RpcRequest>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const RpcRequest &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const RpcRequest &from) { RpcRequest::MergeImpl(*this, from); }

private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(RpcRequest *other);

private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() { return "rpc.RpcRequest"; }

protected:
    explicit RpcRequest(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned = false);

public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int {
        kServiceNameFieldNumber = 1,
        kMethodNameFieldNumber = 2,
        kRequestIdFieldNumber = 3,
        kBodyFieldNumber = 4,
    };
    // string service_name = 1;
    void clear_service_name();
    const std::string &service_name() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_service_name(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_service_name();
    PROTOBUF_NODISCARD std::string *release_service_name();
    void set_allocated_service_name(std::string *service_name);

private:
    const std::string &_internal_service_name() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(const std::string &value);
    std::string *_internal_mutable_service_name();

public:
    // string method_name = 2;
    void clear_method_name();
    const std::string &method_name() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_method_name(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_method_name();
    PROTOBUF_NODISCARD std::string *release_method_name();
    void set_allocated_method_name(std::string *method_name);

private:
    const std::string &_internal_method_name() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_method_name(const std::string &value);
    std::string *_internal_mutable_method_name();

public:
    // string request_id = 3;
    void clear_request_id();
    const std::string &request_id() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_request_id(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_request_id();
    PROTOBUF_NODISCARD std::string *release_request_id();
    void set_allocated_request_id(std::string *request_id);

private:
    const std::string &_internal_request_id() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string &value);
    std::string *_internal_mutable_request_id();

public:
    // bytes body = 4;
    void clear_body();
    const std::string &body() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_body(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_body();
    PROTOBUF_NODISCARD std::string *release_body();
    void set_allocated_body(std::string *body);

private:
    const std::string &_internal_body() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_body(const std::string &value);
    std::string *_internal_mutable_body();

public:
    // @@protoc_insertion_point(class_scope:rpc.RpcRequest)
private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_ {
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_name_;
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_;
        mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union {
        Impl_ _impl_;
    };
    friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class RpcResponse final
    : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rpc.RpcResponse) */ {
public:
    inline RpcResponse() : RpcResponse(nullptr) {}
    ~RpcResponse() override;
    explicit PROTOBUF_CONSTEXPR RpcResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    RpcResponse(const RpcResponse &from);
    RpcResponse(RpcResponse &&from) noexcept : RpcResponse() { *this = ::std::move(from); }

    inline RpcResponse &operator=(const RpcResponse &from) {
        CopyFrom(from);
        return *this;
    }
    inline RpcResponse &operator=(RpcResponse &&from) noexcept {
        if (this == &from) return *this;
        if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
            && GetOwningArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        ) {
            InternalSwap(&from);
        } else {
            CopyFrom(from);
        }
        return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor() { return GetDescriptor(); }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor() {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection() {
        return default_instance().GetMetadata().reflection;
    }
    static const RpcResponse &default_instance() { return *internal_default_instance(); }
    static inline const RpcResponse *internal_default_instance() {
        return reinterpret_cast<const RpcResponse *>(&_RpcResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 1;

    friend void swap(RpcResponse &a, RpcResponse &b) { a.Swap(&b); }
    inline void Swap(RpcResponse *other) {
        if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetOwningArena() != nullptr && GetOwningArena() == other->GetOwningArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetOwningArena() == other->GetOwningArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        } else {
            ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(RpcResponse *other) {
        if (other == this) return;
        GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    RpcResponse *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final {
        return CreateMaybeMessage<RpcResponse>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const RpcResponse &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const RpcResponse &from) { RpcResponse::MergeImpl(*this, from); }

private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(RpcResponse *other);

private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() { return "rpc.RpcResponse"; }

protected:
    explicit RpcResponse(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned = false);

public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int {
        kRequestIdFieldNumber = 1,
        kMsgFieldNumber = 3,
        kBodyFieldNumber = 4,
        kCodeFieldNumber = 2,
    };
    // string request_id = 1;
    void clear_request_id();
    const std::string &request_id() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_request_id(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_request_id();
    PROTOBUF_NODISCARD std::string *release_request_id();
    void set_allocated_request_id(std::string *request_id);

private:
    const std::string &_internal_request_id() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string &value);
    std::string *_internal_mutable_request_id();

public:
    // string msg = 3;
    void clear_msg();
    const std::string &msg() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_msg(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_msg();
    PROTOBUF_NODISCARD std::string *release_msg();
    void set_allocated_msg(std::string *msg);

private:
    const std::string &_internal_msg() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string &value);
    std::string *_internal_mutable_msg();

public:
    // bytes body = 4;
    void clear_body();
    const std::string &body() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_body(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_body();
    PROTOBUF_NODISCARD std::string *release_body();
    void set_allocated_body(std::string *body);

private:
    const std::string &_internal_body() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_body(const std::string &value);
    std::string *_internal_mutable_body();

public:
    // int32 code = 2;
    void clear_code();
    int32_t code() const;
    void set_code(int32_t value);

private:
    int32_t _internal_code() const;
    void _internal_set_code(int32_t value);

public:
    // @@protoc_insertion_point(class_scope:rpc.RpcResponse)
private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_ {
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
        ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_;
        int32_t code_;
        mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union {
        Impl_ _impl_;
    };
    friend struct ::TableStruct_rpc_2eproto;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RpcRequest

// string service_name = 1;
inline void RpcRequest::clear_service_name() { _impl_.service_name_.ClearToEmpty(); }
inline const std::string &RpcRequest::service_name() const {
    // @@protoc_insertion_point(field_get:rpc.RpcRequest.service_name)
    return _internal_service_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcRequest::set_service_name(ArgT0 &&arg0, ArgT... args) {

    _impl_.service_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcRequest.service_name)
}
inline std::string *RpcRequest::mutable_service_name() {
    std::string *_s = _internal_mutable_service_name();
    // @@protoc_insertion_point(field_mutable:rpc.RpcRequest.service_name)
    return _s;
}
inline const std::string &RpcRequest::_internal_service_name() const { return _impl_.service_name_.Get(); }
inline void RpcRequest::_internal_set_service_name(const std::string &value) {

    _impl_.service_name_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcRequest::_internal_mutable_service_name() {

    return _impl_.service_name_.Mutable(GetArenaForAllocation());
}
inline std::string *RpcRequest::release_service_name() {
    // @@protoc_insertion_point(field_release:rpc.RpcRequest.service_name)
    return _impl_.service_name_.Release();
}
inline void RpcRequest::set_allocated_service_name(std::string *service_name) {
    if (service_name != nullptr) {

    } else {
    }
    _impl_.service_name_.SetAllocated(service_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.service_name_.IsDefault()) {
        _impl_.service_name_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcRequest.service_name)
}

// string method_name = 2;
inline void RpcRequest::clear_method_name() { _impl_.method_name_.ClearToEmpty(); }
inline const std::string &RpcRequest::method_name() const {
    // @@protoc_insertion_point(field_get:rpc.RpcRequest.method_name)
    return _internal_method_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcRequest::set_method_name(ArgT0 &&arg0, ArgT... args) {

    _impl_.method_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcRequest.method_name)
}
inline std::string *RpcRequest::mutable_method_name() {
    std::string *_s = _internal_mutable_method_name();
    // @@protoc_insertion_point(field_mutable:rpc.RpcRequest.method_name)
    return _s;
}
inline const std::string &RpcRequest::_internal_method_name() const { return _impl_.method_name_.Get(); }
inline void RpcRequest::_internal_set_method_name(const std::string &value) {

    _impl_.method_name_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcRequest::_internal_mutable_method_name() {

    return _impl_.method_name_.Mutable(GetArenaForAllocation());
}
inline std::string *RpcRequest::release_method_name() {
    // @@protoc_insertion_point(field_release:rpc.RpcRequest.method_name)
    return _impl_.method_name_.Release();
}
inline void RpcRequest::set_allocated_method_name(std::string *method_name) {
    if (method_name != nullptr) {

    } else {
    }
    _impl_.method_name_.SetAllocated(method_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.method_name_.IsDefault()) {
        _impl_.method_name_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcRequest.method_name)
}

// string request_id = 3;
inline void RpcRequest::clear_request_id() { _impl_.request_id_.ClearToEmpty(); }
inline const std::string &RpcRequest::request_id() const {
    // @@protoc_insertion_point(field_get:rpc.RpcRequest.request_id)
    return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcRequest::set_request_id(ArgT0 &&arg0, ArgT... args) {

    _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcRequest.request_id)
}
inline std::string *RpcRequest::mutable_request_id() {
    std::string *_s = _internal_mutable_request_id();
    // @@protoc_insertion_point(field_mutable:rpc.RpcRequest.request_id)
    return _s;
}
inline const std::string &RpcRequest::_internal_request_id() const { return _impl_.request_id_.Get(); }
inline void RpcRequest::_internal_set_request_id(const std::string &value) {

    _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcRequest::_internal_mutable_request_id() {

    return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string *RpcRequest::release_request_id() {
    // @@protoc_insertion_point(field_release:rpc.RpcRequest.request_id)
    return _impl_.request_id_.Release();
}
inline void RpcRequest::set_allocated_request_id(std::string *request_id) {
    if (request_id != nullptr) {

    } else {
    }
    _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.request_id_.IsDefault()) {
        _impl_.request_id_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcRequest.request_id)
}

// bytes body = 4;
inline void RpcRequest::clear_body() { _impl_.body_.ClearToEmpty(); }
inline const std::string &RpcRequest::body() const {
    // @@protoc_insertion_point(field_get:rpc.RpcRequest.body)
    return _internal_body();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcRequest::set_body(ArgT0 &&arg0, ArgT... args) {

    _impl_.body_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcRequest.body)
}
inline std::string *RpcRequest::mutable_body() {
    std::string *_s = _internal_mutable_body();
    // @@protoc_insertion_point(field_mutable:rpc.RpcRequest.body)
    return _s;
}
inline const std::string &RpcRequest::_internal_body() const { return _impl_.body_.Get(); }
inline void RpcRequest::_internal_set_body(const std::string &value) {

    _impl_.body_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcRequest::_internal_mutable_body() { return _impl_.body_.Mutable(GetArenaForAllocation()); }
inline std::string *RpcRequest::release_body() {
    // @@protoc_insertion_point(field_release:rpc.RpcRequest.body)
    return _impl_.body_.Release();
}
inline void RpcRequest::set_allocated_body(std::string *body) {
    if (body != nullptr) {

    } else {
    }
    _impl_.body_.SetAllocated(body, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.body_.IsDefault()) {
        _impl_.body_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcRequest.body)
}

// -------------------------------------------------------------------

// RpcResponse

// string request_id = 1;
inline void RpcResponse::clear_request_id() { _impl_.request_id_.ClearToEmpty(); }
inline const std::string &RpcResponse::request_id() const {
    // @@protoc_insertion_point(field_get:rpc.RpcResponse.request_id)
    return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcResponse::set_request_id(ArgT0 &&arg0, ArgT... args) {

    _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcResponse.request_id)
}
inline std::string *RpcResponse::mutable_request_id() {
    std::string *_s = _internal_mutable_request_id();
    // @@protoc_insertion_point(field_mutable:rpc.RpcResponse.request_id)
    return _s;
}
inline const std::string &RpcResponse::_internal_request_id() const { return _impl_.request_id_.Get(); }
inline void RpcResponse::_internal_set_request_id(const std::string &value) {

    _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcResponse::_internal_mutable_request_id() {

    return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string *RpcResponse::release_request_id() {
    // @@protoc_insertion_point(field_release:rpc.RpcResponse.request_id)
    return _impl_.request_id_.Release();
}
inline void RpcResponse::set_allocated_request_id(std::string *request_id) {
    if (request_id != nullptr) {

    } else {
    }
    _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.request_id_.IsDefault()) {
        _impl_.request_id_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcResponse.request_id)
}

// int32 code = 2;
inline void RpcResponse::clear_code() { _impl_.code_ = 0; }
inline int32_t RpcResponse::_internal_code() const { return _impl_.code_; }
inline int32_t RpcResponse::code() const {
    // @@protoc_insertion_point(field_get:rpc.RpcResponse.code)
    return _internal_code();
}
inline void RpcResponse::_internal_set_code(int32_t value) { _impl_.code_ = value; }
inline void RpcResponse::set_code(int32_t value) {
    _internal_set_code(value);
    // @@protoc_insertion_point(field_set:rpc.RpcResponse.code)
}

// string msg = 3;
inline void RpcResponse::clear_msg() { _impl_.msg_.ClearToEmpty(); }
inline const std::string &RpcResponse::msg() const {
    // @@protoc_insertion_point(field_get:rpc.RpcResponse.msg)
    return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcResponse::set_msg(ArgT0 &&arg0, ArgT... args) {

    _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcResponse.msg)
}
inline std::string *RpcResponse::mutable_msg() {
    std::string *_s = _internal_mutable_msg();
    // @@protoc_insertion_point(field_mutable:rpc.RpcResponse.msg)
    return _s;
}
inline const std::string &RpcResponse::_internal_msg() const { return _impl_.msg_.Get(); }
inline void RpcResponse::_internal_set_msg(const std::string &value) {

    _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcResponse::_internal_mutable_msg() { return _impl_.msg_.Mutable(GetArenaForAllocation()); }
inline std::string *RpcResponse::release_msg() {
    // @@protoc_insertion_point(field_release:rpc.RpcResponse.msg)
    return _impl_.msg_.Release();
}
inline void RpcResponse::set_allocated_msg(std::string *msg) {
    if (msg != nullptr) {

    } else {
    }
    _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.msg_.IsDefault()) {
        _impl_.msg_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcResponse.msg)
}

// bytes body = 4;
inline void RpcResponse::clear_body() { _impl_.body_.ClearToEmpty(); }
inline const std::string &RpcResponse::body() const {
    // @@protoc_insertion_point(field_get:rpc.RpcResponse.body)
    return _internal_body();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE void RpcResponse::set_body(ArgT0 &&arg0, ArgT... args) {

    _impl_.body_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:rpc.RpcResponse.body)
}
inline std::string *RpcResponse::mutable_body() {
    std::string *_s = _internal_mutable_body();
    // @@protoc_insertion_point(field_mutable:rpc.RpcResponse.body)
    return _s;
}
inline const std::string &RpcResponse::_internal_body() const { return _impl_.body_.Get(); }
inline void RpcResponse::_internal_set_body(const std::string &value) {

    _impl_.body_.Set(value, GetArenaForAllocation());
}
inline std::string *RpcResponse::_internal_mutable_body() { return _impl_.body_.Mutable(GetArenaForAllocation()); }
inline std::string *RpcResponse::release_body() {
    // @@protoc_insertion_point(field_release:rpc.RpcResponse.body)
    return _impl_.body_.Release();
}
inline void RpcResponse::set_allocated_body(std::string *body) {
    if (body != nullptr) {

    } else {
    }
    _impl_.body_.SetAllocated(body, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.body_.IsDefault()) {
        _impl_.body_.Set("", GetArenaForAllocation());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
        // @@protoc_insertion_point(field_set_allocated:rpc.RpcResponse.body)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
